**Case Study: Stemming vs. Lemmatization in Sentiment Analysis of Movie Reviews**

**Objective:**
To compare the effectiveness of Stemming (using Porter Stemmer) and Lemmatization (using WordNetLemmatizer) in preprocessing text data for sentiment classification, evaluating their impact on model accuracy.

---

### Step 1: Import and Load Data

In [1]:
import nltk
import random # To shuffle data samples.
import pandas as pd

from nltk.corpus import movie_reviews # Dataset containing labeled movie reviews.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag # Assigns part-of-speech tags (needed for Lemmatization).
from nltk.corpus import wordnet
import re #For regex-based text cleaning.

In [2]:
# Following all download statements, once executed, should be commented, so
# it wont download everytime one execute program.

nltk.download('movie_reviews')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

# Downloads a pre-trained part-of-speech (POS) tagger for NLTK,
# enabling word tagging (e.g., noun, verb) to improve lemmatization accuracy.

nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
movie_reviews

In [5]:
# Load and shuffle 100 positive and 100 negative reviews

docs =[(movie_reviews.raw(fileid), category)
       for category in movie_reviews.categories()
       for fileid in movie_reviews.fileids(category)]

In [4]:
# Step 1: Get categories
# categories = ['neg', 'pos']

# docs = []
# for category in categories:  # Step 2: Outer Loop (category = 'neg' $\rightarrow$ 'pos')
#       fileids = movie_reviews.fileids(category)  # Step 3: Get file IDs for category
#       for fileid in fileids:  # Step 4: Inner Loop (each file)
#           text = movie_reviews.raw(fileid)  # Step 5: Read review text
#           docs.append((text, category))  # Step 6-7: Store (text, label)

# For each category, retrieves a list of file IDs
# (e.g., ['neg/cv000_29416.txt', 'neg/cv001_19502.txt', ...]).

# [("This movie was terrible...", "neg"),
#  ("I loved this film!", "pos"),

In [6]:
random.shuffle(docs)
docs = docs[:200] # first 200 reviews
docs

[('what were they thinking ? \nnostalgia for the seventies is bad enough , but do we really need an eighties film ? \nrobbie hart ( adam sandler ) used to want to be a rock and roll star , but in 1985 he\'s singing at weddings and having a good time . \na romantic at heart , he loves weddings and is just about to get married to his high-school sweetie . \nwhen she leaves him waiting at the altar , his tune changes to " love stinks " . \nhe meets waitress julia ( drew barrymore ) who is engaged to a junk-bonds salesman and you know that they are going to get together . \nin fact you know everything that is going to happen during this movie . \nsandler is somewhat adequate in his leading man role , but there is no spark . \nbarrymore doesn\'t seem to be able to convey anything other than a pretty face with nothing behind it : beauty but no attitude . \nboth characters are just there . \nbit parts by steve buscemi and jon lovitz steal the show . \nthe eighties are shoved in our face . \nreferences to deloreans , madonna , " dallas " , ivana and donald , burt and loni and " miami vice " get old fast . \nthe filmmakers must have realized that there wasn\'t much entertainment to the story and thought they could dazzle the audience with humorous period allusions . \nthey\'re not funny and it doesn\'t work . \nwith change on all fronts accelerating more and more , nostalgia appears to have a great appeal , but don\'t you think we could have more than 14 years before we yearn for the past . \nmaybe we can look forward to a film next year waxing nostalgically about el nino . \n ( michael redman has written this column for over 23 years and he knows that nostalgia is not what it used to be . ) \n',
  'neg'),
 ('sometimes a movie comes along that falls somewhat askew of the rest . \nsome people call it " original " or " artsy " or " abstract " . \nsome people simply call it " trash " . \na life less ordinary is sure to bring about mixed feelings . \ndefinitely a generation-x aimed movie , a life less ordinary has everything from claymation to profane angels to a karaoke-based musical dream sequence . \nwhew ! \nanyone in their 30\'s or above is probably not going to grasp what can be enjoyed about this film . \nit\'s somewhat silly , it\'s somewhat outrageous , and it\'s definitely not your typical romance story , but for the right audience , it works . \na lot of hype has been surrounding this film due to the fact that it comes to us from the same team that brought us trainspotting . \nwell sorry folks , but i haven\'t seen trainspotting so i can\'t really compare . \nwhether that works in this film\'s favor or not is beyond me . \nbut i do know this : ewan mcgregor , whom i had never had the pleasure of watching , definitely charmed me . \nhe was great ! \ncameron diaz\'s character was uneven and a bit hard to grasp . \nthe audience may find it difficult to care about her , thus discouraging the hopes of seeing her unite with mcgregor after we are immediately sucked into caring about and identifying with him . \nmisguided ? \nyou bet . \nloveable ? \nyou bet . \na life less ordinary was a delight and even had a bonus for me when i realized it was filmed in my hometown of salt lake city , utah . \nthis was just one more thing i didn\'t know about this movie when i sat down with a five dollar order of nachos and a three dollar coke . \nmaybe not knowing the premise behind this film made for a pleasant surprise , but i think even if i had known , i would have been just as happy . \na life less ordinary is quirky , eccentric , and downright charming ! \nnot for everyone , but a definite change of pace for your typical night at the movies . \n',
  'pos'),
 ('while watching " shallow grave , " i found myself periodically noticing thematic similarities to the coens\' " blood simple . " \nboth are good films in which several characters , none of whom are the most conscientious to have walked the earth but still are not really evil , indulge in an act of deception that soon necessitates more serious crimes . \nthe body count rises , and before long seemingly normal people have blood on their hands . \nboth films are also flawed , but for different reasons . \n " blood simple " is unrelentingly dark and moody , but its characterizations were a little hollow . \n " shallow grave , " on the other hand , is nearly flawless for an hour and twenty minutes , and then the filmmakers throw away much of what they\'d accomplished for a more standard , audience-pleasing ending . \nthe events of the film were sufficiently intense and disturbing that i honestly felt quite troubled by what i was witnessing on screen most of the time , yet there was a slight grin on my face at the end . \nas the film begins , we are introduced to alex ( ewan mcgregor ) , juliet ( kerry fox ) , and david ( christopher eccleston ) , a scottish trio living in an apartment in glasgow . \nthey are all sarcastic and occasionally obnoxious , but other than that they seem like a fairly normal bunch . \na man named hugo moves into the apartment\'s remaining vacancy , and the next morning he is found dead of a drug overdose . \njuliet is about to call the police when alex discovers that hugo had brought with him a suitcase filled to the brim with cash ( presumably from criminal activities ) . \nthe three eventually decide to keep the money and cover up the death ; after a drawing of straws , the particularly unenviable task of mutilating the body so as to make it unidentifiable and burying it falls to david , who had been the most reluctant to partake in the scheme from the beginning . \nall of this transpires in the first twenty minutes or so of the film , and part of what makes " shallow grave " so brilliant for a while is that i honestly had no idea what was coming next . \nother than the obvious question of why they don\'t report the death and simply hide the cash , which is not addressed , the plotting and characterization , while sometimes predictable , worked in a way that kept my attention and , on more than one occasion , gave me chills . \ni will , therefore , attempt to continue this review in a way that doesn\'t give away too much of the plot . \nbroadly , the trio are in danger due to hugo\'s underworld connections , as two goons search for the money and kill several people in the process . \na police inspector ( ken stott ) is clearly suspicious and visits the apartment , asking pointed questions and trying to unnerve the three suspects by exchanging banal and weirdly humorous bits of dialogue with a junior detective . \ndavid , meanwhile , becomes increasingly paranoid , moves into the attic , and develops an affinity for sharp objects . \ndirector danny boyle effectively creates an atmosphere of mounting tension and suspicion in the apartment , and finally the three seem ready to turn against each other . \nwhile i do not consider myself the " happy endings are automatically stupid " type , i thought that " shallow grave " really should have ended in tragedy - a realistic analysis of the story up to the last ten minutes of the film would indicate that all three characters were probably about to end up in prison , in the mental hospital , or in the morgue . \nthis could have been accomplished , quite credibly , but then boyle and screenwriter john hodge seem to flinch and opt for a more conventional " caper " ending in which we get a kick out of seeing who outsmarted whom , and nothing more . \ngranted , this isn\'t really a " happy " ending , but it\'s still pretty light-hearted compared to what preceded it . \ni really shouldn\'t say anything more about the ending as far as details go , but let me add that it seemed not only shallow and lazy but also inconsistent with the rest of the film and not very believable . \nyes , this ending made me crack a smile for a couple of minutes , but ultimately it left me feeling as if i\'d been cheated . \nstill , " shallow grave " was brilliant most of the way through , and it does at least meet the minimum requirements for an entertaining thriller , and i am therefore awarding it three stars . \ni guess i just can\'t help but think about that fourth star that boyle and hodge let slip away . \n',
  'pos'),
 ('sometimes a stellar cast can compensate for a lot of things , and " pushing tin " certainly features some name stars who are going places : billy bob thornton , cate blanchett , angelina jolie , and oh yes john cusack who might not realize it at first , but he\'s actually the * veteran * among this quartet of fine-looking people . \nsometimes a terrific cast like this can compensate for a lackluster screen treatment of an idea that has " hip comedy " written all over it , compensate for workmanlike but uninspired direction , compensate for an obnoxious score that would have anyone but the tone deaf screaming for the exits , compensate for clich ? d characterizations , compensate for embarrassing " you have to be joking " situations . \netc . \nin " pushing tin , " thornton , blanchett , jolie , and cusack don\'t have an earthly . \nfrom the opening sequence the film is in big trouble : squiggly , " quirky " credits , fake-looking passenger planes circling new york , and anne dudley\'s in-your-ear music making us wonder how she ever got that best original score nomination for " the full monty , " let alone won it . \nbut i , for one , wasn\'t ready to walk just yet . \nso quickly we descend into a tightly-edited air traffic controllers montage which screams to us in large capital letters these people have a difficult job , yes , what with their frantic , mile-a-minute instructional personas , juggling planes and passenger\'s lives like some huge , real , mid-air video game . \nhip , cool , demonic auctioneer nick " the zone " falzone ( cusack ) is the best in the biz . \nof course . \nuntil some hipper , cooler , leather-clad flyboy assist in the guise of russell bell ( thornton ) shows up to challenge falzone\'s finite air space . \nboys will be boys and some heavy duty testosterone starts exuding , then the macho one-upmanship begins . \nit doesn\'t stop with seeing who can juggle three 747s within a cat\'s whisker of each other . \noh no . \nthere are some broken hoop dreams , some wanna-see-how-fast-i-can-drives , and then the ultimate showdown : was that my wife i saw you with last night ? \ndirector mike newell ( " four weddings and a funeral " ) must have read a different draft of this script because the one that\'s being acted out up there between newark , jfk , and la guardia doesn\'t have an ounce of subtlety , and newell has made some awfully good-and funny-movies before . \nthe antics of these air traffic controllers will make you cringe . \nthey\'ll make you frown in disbelief . \nthey\'ll have you constantly looking at your watch . \nbut wait ! \nthere\'s still 100 minutes to go ! ! \nthe film\'s only saving grace is blanchett , whose connie falzone is a spunky , brash , long island housewife who wants to better herself by taking art classes . \nthis is a wonderful accomplishment for the fine actress who has previously played a red-headed australian gambler ( " oscar and lucinda " ) and a tempestuous british monarch ( " elizabeth " ) . \nbut she\'s not enough to save the picture . \nthornton looks terrific and performs solidly but his character is a joke . \njolie ( as russell\'s knock \'em dead wife ) isn\'t bad , but the up-and-coming actress disappoints by allowing herself to be displayed like a plaything . \ncusack cracks gum , dons shades , and acts hip throughout but , like everything else in the film , his performance is forced . \nin the last ten minutes or so , for some inexplicable reason , things start coming together and you begin to get a sense of how this film might have been , like the trailer teases . \nbut it\'s too little too late . \na fine cast aside , " pushing tin " is nothing more than an embarrassment . \n',
  'neg'),
 ('the previews for the movie are pretty good . \nthey show a little plot , all the characters , and the emotional highlights , all spliced together to give a general impression of the script . \nunfortunately , the full movie adds nothing but 115 minutes . \nthe residents of mystery love hockey . \nmystery and hockey go together like texas and high school football . \nthe townsfolk love hockey so much that they even acquit a player who\'s guilty of shooting another man ( yes , that\'s one of the movie\'s jokes . ) \nevery saturday , the best players pair off for a game , and the whole town comes to watch . \nthe town\'s prodigal son charlie ( hank azaria ) wrote an article on the weekly game for sports illustrated . \nmystery\'s national fame has the town abuzz . \na week later , charlie actually shows up in person , and he brings with him an offer from the nhl . \nthe new york rangers will come to mystery to play the locals . \nthe mysterians see this as both good and bad . \non the one hand , they\'d love to have the fame and the money of such an exhibition . \non the other hand , they don\'t want to turn up as the butt of leno and letterman jokes . \nthe movie follows a handful of lives that are affected by the proposition . \nbiebe ( russell crowe ) has just been retired from the team and is asked to coach the boys , including his new replacement . \nhe\'s already resentful , and to top it off charlie has been making eyes at his wife . \ncrowe is not given a lot of room to act in this film , so he\'s just kind of stuck with constantly brooding . \ncharlie , meanwhile , is resentful of having born in a town where hockey is the only measure of a man\'s worth . \nhis " gift " of the feature story , and of the new york rangers , was his way of compensating for not being a better skater . \nhe hoped it would earn him some respect and merit , but the townspeople find reasons to continue disliking him . \nburt reynolds could have been interesting as walter , the judge whose courtroom was befouled by a moronic jury of hockey fans . \nwalter actually has some experience with collegiate hockey , but he actively tries to put it behind him . \nhe wants his son to take the game more seriously , but he wants his community to just get over it . \nreynolds could have been good , but sloppy writing and/or editing keep walter in the corner , and so reynolds never really gets to pull his performance all together . \none character actually was interesting . \nbiebe\'s wife ( mary mccormack ) , like the judge , understood that there was more to life than hockey . \nbut unlike him she has come to accept the skewed view of the community . \nshe chose the town and her husband with her eyes wide open . \nher unique insight is verbalized once , and it lasts only a scene before it is gone , but her performance carries the hint of some deeper wisdom . \nmysterty , alaska follows a handful of other characters , but none are well developed or worth mentioning . \nthe biggest problem with this movie is that there is no real heart to the story , no underlying thing that the movie is really about . \ninstead , roach and screenwriters david e . kelley and sean o\'byrne try to cram the entire human condition into this sports comedy . \nthey try to make you laugh and cry , to feel outrage and pride . \nthey present the framing and cadence for jokes , but there\'s nothing truly funny . \nthey show appropriately staged scenes of sadness , but they give you nothing to be really sad about . \nas columnist molly ivins would say , it\'s all hat , no cattle . \nthe perfect opportunity arises for roach to say what this movie is really about . \nthere is a funeral scene , played with appropriate gravity and somber music . \nit is a chance for the characters to reflect on their lives and decide what\'s truly important . \nrussell crowe steps forward to speak , about to spell out the movie\'s metaphor for us . \nhe says that what really matters in life is " community . . . . " \nthen adds " and hockey . " \ni guess these mysterians really are as shallow as they appear . \nonly mildly bad , mystery , alaska probably deserves 2 stars . \ni even laughed out loud , genuine laughs in places . \nbut i docked it an extra half star when mike myers , a friend of roach , turned up in a role that didn\'t suit him . \nmyers is a comic character actor . \nhe puts on masks , becomes an outrageous caricature , and is funny . \nhe\'s great as austin powers , dr . evil , or any of his scottish characters . \nnobody else in mysterty , alaska is a comic caricature . \nall the other people have the feel of dramatic characters in semi-serious roles . \nfor roach to bring in myers for a few cheap laughs shows incredible contempt toward the rest of his cast , toward his audience , and indeed toward the film itself . \nit\'s an acknowledgment by the director that the film is not worth taking seriously . \n',
  'neg'),

In [7]:
df = pd.DataFrame(docs, columns= ['review', 'label'])
df['label'] = df['label'].map({'pos': 1, 'neg':0})

In [8]:
df.head()

                                              review  label
0  what were they thinking ? \nnostalgia for the ...      0
1  sometimes a movie comes along that falls somew...      1
2  while watching " shallow grave , " i found mys...      1
3  sometimes a stellar cast can compensate for a ...      0
4  the previews for the movie are pretty good . \...      0

In [9]:
df.tail()

                                                review  label
195  much ballyhoo has been made over this new vers...      1
196  if you don't think kevin kline in drag is funn...      0
197  it was once said that in order to truly enjoy ...      0
198  there was probably a good reason that the warn...      0
199  in the finale of disney's " mighty joe young ,...      0

In [10]:
df.columns

Index(['review', 'label'], dtype='str')

In [11]:
df['label'].value_counts()

label
1    101
0     99
Name: count, dtype: int64

# step 2: text cleaning

In [12]:
def clean_text(text):
    text = text.lower() # Lowercase all text
    
    text = re.sub(r"[^\w\s]", "", text) # Remove punctuation , re is module for regex (regular expression)
    
    return text

df["clean"] = df["review"].apply(clean_text)

In [13]:
#Removes punctuation using regex (^^\w\s keeps only words/whitespace).

In [14]:
df['clean'].head()

0    what were they thinking  \nnostalgia for the s...
1    sometimes a movie comes along that falls somew...
2    while watching  shallow grave   i found myself...
3    sometimes a stellar cast can compensate for a ...
4    the previews for the movie are pretty good  \n...
Name: clean, dtype: str

In [15]:
def get_wordnet_pos(tag):
    if tag.startswith("J"):
        return wordnet.ADJ
    elif tag.startswith("V"):
        return wordnet.VERB
    elif tag.startswith("N"):
        return wordnet.NOUN
    elif tag.startswith("R"):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [16]:
stop_words = set(stopwords.words('english')) - {'not','no', 'never'}

# removing negative words from stop word, so it can be used for sentiment analysis.

In [17]:
#Stemming

stemmer = PorterStemmer()
def stem_pipeline(text):
    tokens = word_tokenize(text)
    filtered = [w for w in tokens if w not in stop_words]
    stemmed = [stemmer.stem(w) for w in filtered]
    return " ".join(stemmed)

# stemming process to text

In [20]:
df['stemmed'] = df['clean'].apply(stem_pipeline)

In [21]:
df['stemmed'].head()

0    think nostalgia seventi bad enough realli need...
1    sometim movi come along fall somewhat askew re...
2    watch shallow grave found period notic themat ...
3    sometim stellar cast compens lot thing push ti...
4    preview movi pretti good show littl plot chara...
Name: stemmed, dtype: str

# lemmatization

In [22]:
lemmatizer = WordNetLemmatizer()
def lemma_pipeline(text):
    tokens = word_tokenize(text)
    filtered = [w for w in tokens if w not in stop_words]
    pos_tags = pos_tag(filtered)
    lemmatized = [lemmatizer.lemmatize(w, get_wordnet_pos(tag)) for w, tag in pos_tags]
    return " ".join(lemmatized)

# defined function for lemmatizing process.

In [24]:
nltk.download('averaged_perceptron_tagger_eng')

df['lemmatized'] = df['clean'].apply(lemma_pipeline)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\skuch\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

In [25]:
df['lemmatized'].head()

0    think nostalgia seventy bad enough really need...
1    sometimes movie come along fall somewhat askew...
2    watch shallow grave find periodically noticing...
3    sometimes stellar cast compensate lot thing pu...
4    preview movie pretty good show little plot cha...
Name: lemmatized, dtype: str

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
# Converts text to numerical TF-IDF feature vectors for machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# Prepare data
X_stem = df["stemmed"]
X_lemma = df["lemmatized"]
y = df["label"]

In [29]:
X_stem.head()

0    think nostalgia seventi bad enough realli need...
1    sometim movi come along fall somewhat askew re...
2    watch shallow grave found period notic themat ...
3    sometim stellar cast compens lot thing push ti...
4    preview movi pretti good show littl plot chara...
Name: stemmed, dtype: str

In [28]:
X_lemma.head()

0    think nostalgia seventy bad enough really need...
1    sometimes movie come along fall somewhat askew...
2    watch shallow grave find periodically noticing...
3    sometimes stellar cast compensate lot thing pu...
4    preview movie pretty good show little plot cha...
Name: lemmatized, dtype: str

In [30]:
y.head()

0    0
1    1
2    1
3    0
4    0
Name: label, dtype: int64

In [31]:
# stemming data split
X_train_s, X_test_s, y_train, y_test = train_test_split(X_stem, y, test_size=0.2, random_state=42)

# lemit data split
X_train_l, X_test_l, _, _ = train_test_split(X_lemma, y, test_size=0.2, random_state=42)

# y_train and y_test are same for both, hence here skipped by writing _, _

In [33]:
X_train_s.shape

(160,)

In [34]:
y_train.shape

(160,)

In [35]:
# TF-IDF Vectorization

vectorizer = TfidfVectorizer()
X_train_s_vec = vectorizer.fit_transform(X_train_s)
X_test_s_vec = vectorizer.transform(X_test_s)


X_train_l_vec = vectorizer.fit_transform(X_train_l)
X_test_l_vec = vectorizer.transform(X_test_l)

In [36]:
# Train and evaluate
model_s = LogisticRegression(max_iter=1000)

model_s.fit(X_train_s_vec, y_train)

y_pred_s = model_s.predict(X_test_s_vec)

acc_s = accuracy_score(y_test, y_pred_s)

print("Stemming Accuracy:", round(acc_s, 2))

Stemming Accuracy: 0.75

In [37]:
model_l = LogisticRegression(max_iter=1000)

model_l.fit(X_train_l_vec, y_train)

y_pred_l = model_l.predict(X_test_l_vec)

acc_l = accuracy_score(y_test, y_pred_l)

print("Lemmatization Accuracy:", round(acc_l, 2))

Lemmatization Accuracy: 0.75

In [38]:
# Key Observations

# Stemming vs. Lemmatization:
# Stemming is faster but less accurate (e.g., "flies" $\rightarrow$ "fli").
# Lemmatization preserves meaning but requires POS tagging.

# Model Performance:
# Both methods achieved 75% accuracy in this case.
# Lemmatization may outperform in tasks needing semantic precision (e.g., "better" $\rightarrow$ "good").